### ISSUE TITLE
eliminating parentheses for function calls with arguments

### ISSUE THREAD

**Issue by davidedc** [vrok/have#1]
... that would be reducing even more of the residual C noise!

(or, even better, did you look at the transpilation that http://livescript.net/ does? I'd bet plenty of those are not depending on having a dynamic target language, so they could work? )

(awesome project by the way, I'll use this to go close to the metal)

**Comment by vrok** [comment]
It's worth considering, I'll think about it. A small disclaimer though - one of the things I like in Go is how straightforward it is to parse, that allows the parser to be really fast and simple, and I'd like to preserve that in Have. I like the lack of language ambiguities, too.
I've never heard about LiveScript, I'll take a look at it.

Thanks! Great to hear that you like it, but please don't use it for anything serious yet! ;)

**Comment by robert-zaremba** [comment]
Eliminating parentheses for function calls makes the parser way more complex. 
What I like in go is it's explicitly. In my opinion the current syntax is clear and concise enough. When adding new feature one always need to ask two questions:

* what you will win.
* what problems might come.

This feature will increase parser complexity and the code might be more tricky two write / read.

**Comment by vrok** [comment]
Actually, after a few days of thinking about it, I'll be taking the opposite turn - Have syntax will be moving closer to Go. I hope it won't discourage you from giving Have a try, though. ([there's a lengthy explanation on the blog](http://havelang.org/post/embrace_braces/))
Again, thanks!

**Comment by robert-zaremba** [comment]
@vrok +1
