### ISSUE TITLE
-h flag usage

### ISSUE THREAD

**Issue by smithjessk** [vrok/have#7]
Commit: 20fc865cab7bcda1d49de64c4286b600680cd4f5

Great work! Loving some of the ideas in Have.

When the `have` executable is passed the `-h` flag, it prints out a [usage statement](https://golang.org/pkg/flag/#pkg-variables), e.g.:

```
[jess@localhost ~]$ have -h
Usage of have:
[jess@localhost ~]$ 
```

This is caused by the call to `flag.Parse()`. With the call removed, the executable continues on properly (i.e., printing "Arguments missing").

I propose that the `-h` flag list out the arguments that can be passed to `have`, e.g. `trans` and `run`, along with a small explanation for each argument. If you like this design, I would be happy to implement it myself.

**Comment by vrok** [comment]
Makes sense, go ahead if you want
